<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="..\DocumentManagement.API\appsettings.json" Link="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\DocumentManagement.Data\DocumentManagement.Data.csproj" />
	</ItemGroup>
</Project>