// <auto-generated />
using System;
using DocumentManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentManagement.Domain.Migrations
{
    [DbContext(typeof(DocumentContext))]
    [Migration("20260515151956_AddAcademicTables")]
    partial class AddAcademicTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentManagement.Data.DailyReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("DailyReminders");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentComments");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentMetaData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Metatag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentMetaDatas");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeBound")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.HasIndex("RoleId");

                    b.ToTable("DocumentRolePermissions", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentUserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllowDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTimeBound")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentUserPermissions", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentVersions");
                });

            modelBuilder.Entity("DocumentManagement.Data.Dosen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Jenis_Dosen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PegawaiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PegawaiId")
                        .IsUnique();

                    b.ToTable("Dosens", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.DosenTetap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DosenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Golongan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jabatan_Akademik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIDN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor_Serdos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TMT")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DosenId")
                        .IsUnique();

                    b.ToTable("DosenTetaps", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.EmailSMTPSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnableSSL")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailSMTPSettings");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Url");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.DocumentAuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignToRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OperationName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignToRoleId");

                    b.HasIndex("AssignToUserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAuditTrails");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.DocumentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DocumentTokens");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.InfoMahasiswa", b =>
                {
                    b.Property<int>("InfoMahasiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InfoMahasiswaId"));

                    b.Property<int>("JmlhDO")
                        .HasColumnType("int");

                    b.Property<int>("JmlhLulus")
                        .HasColumnType("int");

                    b.Property<int>("JmlhNonAktif")
                        .HasColumnType("int");

                    b.Property<int>("JmlhUndurDiri")
                        .HasColumnType("int");

                    b.Property<int>("JumlahIPKDibawah2")
                        .HasColumnType("int");

                    b.Property<int>("JumlhMBKM")
                        .HasColumnType("int");

                    b.Property<int>("MasaStudi8Sampai10")
                        .HasColumnType("int");

                    b.Property<int>("MasaStudiDiatas10")
                        .HasColumnType("int");

                    b.Property<int>("MasaStudiDibawah8")
                        .HasColumnType("int");

                    b.Property<float>("RataanIPKTotal")
                        .HasColumnType("real");

                    b.Property<int>("ThnMasukId")
                        .HasColumnType("int");

                    b.HasKey("InfoMahasiswaId");

                    b.HasIndex("ThnMasukId")
                        .IsUnique();

                    b.ToTable("InfoMahasiswas", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.NLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Callsite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NLog");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Publikasi", b =>
                {
                    b.Property<Guid>("PublikasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JudulPublikasi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KategoriPublikasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PegawaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PenerapanMasyarakat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TahunPublikasi")
                        .HasColumnType("int");

                    b.HasKey("PublikasiId");

                    b.HasIndex("PegawaiId");

                    b.ToTable("Publikasis");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.TahunAkademik", b =>
                {
                    b.Property<int>("ThnAkademikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThnAkademikId"));

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThnAkademik")
                        .HasColumnType("int");

                    b.HasKey("ThnAkademikId");

                    b.ToTable("TahunAkademiks", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.TahunMasuk", b =>
                {
                    b.Property<int>("ThnMasukId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThnMasukId"));

                    b.Property<int>("ThnAkademikId")
                        .HasColumnType("int");

                    b.Property<int>("ThnMasuk")
                        .HasColumnType("int");

                    b.Property<int>("TotalRegistrasiMhs")
                        .HasColumnType("int");

                    b.HasKey("ThnMasukId");

                    b.HasIndex("ThnAkademikId");

                    b.ToTable("TahunMasuks", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.HalfYearlyReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("HalfYearlyReminders");
                });

            modelBuilder.Entity("DocumentManagement.Data.JenisTempatKerja", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("BUMN")
                        .HasColumnType("int");

                    b.Property<int>("Instansi_Pemerintah")
                        .HasColumnType("int");

                    b.Property<int>("Lainnya")
                        .HasColumnType("int");

                    b.Property<int>("Organisasi_Multilateral")
                        .HasColumnType("int");

                    b.Property<int>("Organisasi_NonProfit")
                        .HasColumnType("int");

                    b.Property<int>("Wirausaha")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("JenisTempatKerjas", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.KegiatanPPM", b =>
                {
                    b.Property<Guid>("KegiatanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DanaPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("JenisPPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudulPPM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MitraPPM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomorKontrak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TahunMulai")
                        .HasColumnType("int");

                    b.Property<int>("TahunSelesai")
                        .HasColumnType("int");

                    b.HasKey("KegiatanID");

                    b.ToTable("KegiatanPPMS", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.LoginAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemoteIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginAudits");
                });

            modelBuilder.Entity("DocumentManagement.Data.MasaTungguKerja", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Diatas6Bulan")
                        .HasColumnType("int");

                    b.Property<int>("Dibawah6Bulan")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("MasaTungguKerjas", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("DocumentManagement.Data.Pegawai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gelar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jenis_Kelamin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jenis_Pegawai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor_BPJS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor_NPWP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomor_Paspor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pendidikan_Terakhir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_Pernikahan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal_Lahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telepon_Darurat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tempat_Lahir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pegawais", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.PegawaiKegiatanPPM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KegiatanID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PegawaiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KegiatanID");

                    b.HasIndex("PegawaiId", "KegiatanID")
                        .IsUnique();

                    b.ToTable("PegawaiKegiatanPPMS", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.PosisiJabatan", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("CoFounder")
                        .HasColumnType("int");

                    b.Property<int>("Founder")
                        .HasColumnType("int");

                    b.Property<int>("Freelancer")
                        .HasColumnType("int");

                    b.Property<int>("Staf")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("PosisiJabatans", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.PrestasiMhs", b =>
                {
                    b.Property<int>("ThnAkademikId")
                        .HasColumnType("int");

                    b.Property<int>("JmlhPKM")
                        .HasColumnType("int");

                    b.Property<int>("JumlhInbound")
                        .HasColumnType("int");

                    b.Property<int>("JumlhLombaInter")
                        .HasColumnType("int");

                    b.Property<int>("JumlhLombaNasional")
                        .HasColumnType("int");

                    b.Property<int>("JumlhMapres")
                        .HasColumnType("int");

                    b.Property<int>("JumlhOutbound")
                        .HasColumnType("int");

                    b.HasKey("ThnAkademikId");

                    b.ToTable("PrestasiMhss", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.QuarterlyReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("QuarterlyReminders");
                });

            modelBuilder.Entity("DocumentManagement.Data.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepeated")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailNotification")
                        .HasColumnType("bit");

                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReminderId");

                    b.ToTable("ReminderNotifications");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderScheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailNotification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("ReminderSchedulers");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderUser", b =>
                {
                    b.Property<Guid>("ReminderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReminderId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ReminderUsers");
                });

            modelBuilder.Entity("DocumentManagement.Data.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("DocumentManagement.Data.ScreenOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ScreenId");

                    b.ToTable("ScreenOperations");
                });

            modelBuilder.Entity("DocumentManagement.Data.SendEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSend")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("SendEmails");
                });

            modelBuilder.Entity("DocumentManagement.Data.StatusLulusan", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("Bekerja")
                        .HasColumnType("int");

                    b.Property<int>("BelumKerja")
                        .HasColumnType("int");

                    b.Property<int>("Berwirausaha")
                        .HasColumnType("int");

                    b.Property<int>("Internship")
                        .HasColumnType("int");

                    b.Property<int>("LanjutStudi")
                        .HasColumnType("int");

                    b.Property<int>("TahunId")
                        .HasColumnType("int");

                    b.Property<int>("Tahun_Input")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.HasIndex("TahunId");

                    b.ToTable("StatusLulusans", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.TahunLulus", b =>
                {
                    b.Property<int>("TahunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TahunId"));

                    b.Property<int>("LulusanTahun")
                        .HasColumnType("int");

                    b.HasKey("TahunId");

                    b.ToTable("TahunLuluss", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.Tendik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Jenis_Tendik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PegawaiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PegawaiId")
                        .IsUnique();

                    b.ToTable("Tendiks", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.TendikTetap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Golongan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jabatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TMT")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TendikId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TendikId")
                        .IsUnique();

                    b.ToTable("TendikTetaps", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.TingkatTempatKerja", b =>
                {
                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Lokal")
                        .HasColumnType("int");

                    b.Property<int>("MultiNasional")
                        .HasColumnType("int");

                    b.Property<int>("Nasional")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.ToTable("TingkatTempatKerjas", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ScreenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("DocumentManagement.Data.DailyReminder", b =>
                {
                    b.HasOne("DocumentManagement.Data.Reminder", "Reminder")
                        .WithMany("DailyReminders")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentComment", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("DocumentComments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentMetaData", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("DocumentMetaDatas")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentRolePermission", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("DocumentRolePermissions")
                        .HasForeignKey("DocumentId")
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Role", "Role")
                        .WithMany("DocumentRolePermissions")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentUserPermission", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("DocumentUserPermissions")
                        .HasForeignKey("DocumentId")
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("DocumentUserPermissions")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.DocumentVersion", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.Dosen", b =>
                {
                    b.HasOne("DocumentManagement.Data.Pegawai", "Pegawai")
                        .WithOne("Dosen")
                        .HasForeignKey("DocumentManagement.Data.Dosen", "PegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pegawai");
                });

            modelBuilder.Entity("DocumentManagement.Data.DosenTetap", b =>
                {
                    b.HasOne("DocumentManagement.Data.Dosen", "Dosen")
                        .WithOne("DosenTetap")
                        .HasForeignKey("DocumentManagement.Data.DosenTetap", "DosenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosen");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Category", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Document", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.DocumentAuditTrail", b =>
                {
                    b.HasOne("DocumentManagement.Data.Role", "AssignToRole")
                        .WithMany()
                        .HasForeignKey("AssignToRoleId");

                    b.HasOne("DocumentManagement.Data.User", "AssignToUser")
                        .WithMany()
                        .HasForeignKey("AssignToUserId");

                    b.HasOne("DocumentManagement.Data.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("DocumentAuditTrails")
                        .HasForeignKey("DocumentId")
                        .IsRequired();

                    b.Navigation("AssignToRole");

                    b.Navigation("AssignToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.InfoMahasiswa", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.TahunMasuk", "TahunMasuk")
                        .WithOne("InfoMahasiswa")
                        .HasForeignKey("DocumentManagement.Data.Entities.InfoMahasiswa", "ThnMasukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunMasuk");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Publikasi", b =>
                {
                    b.HasOne("DocumentManagement.Data.Pegawai", "Pegawai")
                        .WithMany("Publikasis")
                        .HasForeignKey("PegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pegawai");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.TahunMasuk", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.TahunAkademik", "TahunAkademik")
                        .WithMany("TahunMasuks")
                        .HasForeignKey("ThnAkademikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAkademik");
                });

            modelBuilder.Entity("DocumentManagement.Data.HalfYearlyReminder", b =>
                {
                    b.HasOne("DocumentManagement.Data.Reminder", "Reminder")
                        .WithMany("HalfYearlyReminders")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("DocumentManagement.Data.JenisTempatKerja", b =>
                {
                    b.HasOne("DocumentManagement.Data.StatusLulusan", "StatusLulusan")
                        .WithOne("JenisTempatKerja")
                        .HasForeignKey("DocumentManagement.Data.JenisTempatKerja", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusLulusan");
                });

            modelBuilder.Entity("DocumentManagement.Data.MasaTungguKerja", b =>
                {
                    b.HasOne("DocumentManagement.Data.StatusLulusan", "StatusLulusan")
                        .WithOne("MasaTungguKerja")
                        .HasForeignKey("DocumentManagement.Data.MasaTungguKerja", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusLulusan");
                });

            modelBuilder.Entity("DocumentManagement.Data.PegawaiKegiatanPPM", b =>
                {
                    b.HasOne("DocumentManagement.Data.KegiatanPPM", "KegiatanPPM")
                        .WithMany("PegawaiKegiatanPPMs")
                        .HasForeignKey("KegiatanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Pegawai", "Pegawai")
                        .WithMany("PegawaiKegiatanPPMs")
                        .HasForeignKey("PegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KegiatanPPM");

                    b.Navigation("Pegawai");
                });

            modelBuilder.Entity("DocumentManagement.Data.PosisiJabatan", b =>
                {
                    b.HasOne("DocumentManagement.Data.StatusLulusan", "StatusLulusan")
                        .WithOne("PosisiJabatan")
                        .HasForeignKey("DocumentManagement.Data.PosisiJabatan", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusLulusan");
                });

            modelBuilder.Entity("DocumentManagement.Data.PrestasiMhs", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.TahunAkademik", "TahunAkademik")
                        .WithOne("PrestasiMhs")
                        .HasForeignKey("DocumentManagement.Data.PrestasiMhs", "ThnAkademikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAkademik");
                });

            modelBuilder.Entity("DocumentManagement.Data.QuarterlyReminder", b =>
                {
                    b.HasOne("DocumentManagement.Data.Reminder", "Reminder")
                        .WithMany("QuarterlyReminders")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("DocumentManagement.Data.Reminder", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderNotification", b =>
                {
                    b.HasOne("DocumentManagement.Data.Reminder", "Reminder")
                        .WithMany("ReminderNotifications")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderScheduler", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.ReminderUser", b =>
                {
                    b.HasOne("DocumentManagement.Data.Reminder", "Reminder")
                        .WithMany("ReminderUsers")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.RoleClaim", b =>
                {
                    b.HasOne("DocumentManagement.Data.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("DocumentManagement.Data.ScreenOperation", b =>
                {
                    b.HasOne("DocumentManagement.Data.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("DocumentManagement.Data.SendEmail", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentManagement.Data.StatusLulusan", b =>
                {
                    b.HasOne("DocumentManagement.Data.TahunLulus", "TahunLulus")
                        .WithMany("StatusLulusan")
                        .HasForeignKey("TahunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunLulus");
                });

            modelBuilder.Entity("DocumentManagement.Data.Tendik", b =>
                {
                    b.HasOne("DocumentManagement.Data.Pegawai", "Pegawai")
                        .WithOne("Tendik")
                        .HasForeignKey("DocumentManagement.Data.Tendik", "PegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pegawai");
                });

            modelBuilder.Entity("DocumentManagement.Data.TendikTetap", b =>
                {
                    b.HasOne("DocumentManagement.Data.Tendik", "Tendik")
                        .WithOne("TendikTetap")
                        .HasForeignKey("DocumentManagement.Data.TendikTetap", "TendikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tendik");
                });

            modelBuilder.Entity("DocumentManagement.Data.TingkatTempatKerja", b =>
                {
                    b.HasOne("DocumentManagement.Data.StatusLulusan", "StatusLulusan")
                        .WithOne("TingkatTempatKerja")
                        .HasForeignKey("DocumentManagement.Data.TingkatTempatKerja", "StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatusLulusan");
                });

            modelBuilder.Entity("DocumentManagement.Data.UserClaim", b =>
                {
                    b.HasOne("DocumentManagement.Data.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Screen");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.UserLogin", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.UserNotification", b =>
                {
                    b.HasOne("DocumentManagement.Data.Entities.Document", "Document")
                        .WithMany("UserNotifications")
                        .HasForeignKey("DocumentId");

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.UserRole", b =>
                {
                    b.HasOne("DocumentManagement.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.UserToken", b =>
                {
                    b.HasOne("DocumentManagement.Data.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentManagement.Data.Dosen", b =>
                {
                    b.Navigation("DosenTetap");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.Document", b =>
                {
                    b.Navigation("DocumentAuditTrails");

                    b.Navigation("DocumentComments");

                    b.Navigation("DocumentMetaDatas");

                    b.Navigation("DocumentRolePermissions");

                    b.Navigation("DocumentUserPermissions");

                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.TahunAkademik", b =>
                {
                    b.Navigation("PrestasiMhs");

                    b.Navigation("TahunMasuks");
                });

            modelBuilder.Entity("DocumentManagement.Data.Entities.TahunMasuk", b =>
                {
                    b.Navigation("InfoMahasiswa");
                });

            modelBuilder.Entity("DocumentManagement.Data.KegiatanPPM", b =>
                {
                    b.Navigation("PegawaiKegiatanPPMs");
                });

            modelBuilder.Entity("DocumentManagement.Data.Pegawai", b =>
                {
                    b.Navigation("Dosen");

                    b.Navigation("PegawaiKegiatanPPMs");

                    b.Navigation("Publikasis");

                    b.Navigation("Tendik");
                });

            modelBuilder.Entity("DocumentManagement.Data.Reminder", b =>
                {
                    b.Navigation("DailyReminders");

                    b.Navigation("HalfYearlyReminders");

                    b.Navigation("QuarterlyReminders");

                    b.Navigation("ReminderNotifications");

                    b.Navigation("ReminderUsers");
                });

            modelBuilder.Entity("DocumentManagement.Data.Role", b =>
                {
                    b.Navigation("DocumentRolePermissions");

                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DocumentManagement.Data.StatusLulusan", b =>
                {
                    b.Navigation("JenisTempatKerja");

                    b.Navigation("MasaTungguKerja");

                    b.Navigation("PosisiJabatan");

                    b.Navigation("TingkatTempatKerja");
                });

            modelBuilder.Entity("DocumentManagement.Data.TahunLulus", b =>
                {
                    b.Navigation("StatusLulusan");
                });

            modelBuilder.Entity("DocumentManagement.Data.Tendik", b =>
                {
                    b.Navigation("TendikTetap");
                });

            modelBuilder.Entity("DocumentManagement.Data.User", b =>
                {
                    b.Navigation("DocumentUserPermissions");

                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
